# Generated by Django 2.2.1 on 2019-07-19 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room_monitor.DayOfTheWeek'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='room_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room_monitor.RoomAllocation'),
        ),
        migrations.AlterField(
            model_name='roomallocation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room_monitor.Room'),
        ),
    ]
