# Generated by Django 2.2.1 on 2019-07-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_monitor', '0005_auto_20190719_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='power_status',
            new_name='forced_power_state',
        ),
        migrations.AddField(
            model_name='room',
            name='is_forced_power_status',
            field=models.BooleanField(default=False),
        ),
    ]
