# Generated by Django 2.2.1 on 2019-07-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_monitor', '0006_auto_20190720_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='forced_power_state',
            new_name='power_state',
        ),
    ]
